### ISSUE TITLE
Incomplete ReadMe

### ISSUE THREAD

**Issue by meta-human-08** [BlueLearn-Aspireve/Project1-Calculator#1]
In the Readme structure, you haven't mentioned where the asset files go, even though they seem to be an important part in your application
| Screenshot of your ReadMe |
|----|
| ![image](https://github.com/BlueLearn-Aspireve/Project1-Calculator/assets/130368671/9e1a404c-fd98-4f4b-94bc-449db2ac79b3) |

**Comment by Aspireve** [comment]
Ohh, I completely for got about that, why don't you make a PR and solve it
Thanks for informing
